"use client";

import React, { useState } from "react";
import { FolderTree, Layers, Copy, Check, Terminal, FileCode2, Cpu, ArrowRight } from "lucide-react";

type ViewTab = "ecosystem" | "folder-structure" | "mvc";

export function EcosystemGrid() {
  const [activeTab, setActiveTab] = useState<ViewTab>("ecosystem");
  const [copied, setCopied] = useState(false);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const ecosystemContent = `[ THE SPRING ECOSYSTEM ]
├── Spring Boot .........──> Pre-configures and runs applications instantly
│   ├── spring-boot ............... (Core lifecycle, runner setup, and banner logic)
│   ├── spring-boot-autoconfigure . (The "magic" engine that auto-wires beans)
│   ├── spring-boot-actuator ...... (Production-ready monitoring & health endpoints)
│   └── spring-boot-starters ...... (Pre-packaged dependency bundles like starter-web)
│
├── Spring Data .........──> Simplifies SQL/NoSQL database interactions
│   ├── spring-data-commons ....... (The core interfaces & repository abstractions)
│   ├── spring-data-jpa ........... (Relational database management via Hibernate)
│   ├── spring-data-mongodb ....... (NoSQL document storage support)
│   └── spring-data-redis ......... (Key-value memory cache support)
│
├── Spring Security ....──> Handles authentication, authorization, and safety
│   ├── spring-security-core ...... (Core authentication & access control logic)
│   ├── spring-security-web ....... (HTTP security filters and URL blocking rules)
│   ├── spring-security-config .... (The Java configuration fluent API engine)
│   └── spring-security-crypto .... (Password hashing, salts, and encryption tools)
│
├── Spring Cloud .......──> Manages microservices and distributed systems
│   ├── spring-cloud-config ....... (Centralized server for managing environment properties)
│   ├── spring-cloud-gateway ...... (API routing, security, and traffic throttling)
│   └── spring-cloud-stream ....... (Event-driven messaging abstracting Kafka/RabbitMQ)
│
├── Spring Batch .......──> Processes massive volumes of background data
│   ├── spring-batch-infrastructure (Low-level readers, writers, and retry mechanisms)
│   └── spring-batch-core ......... (Job execution lifecycle, steps, and restart logic)
│
├── Spring Integration .──> Connects distinct enterprise systems together
│   ├── spring-integration-core ... (The messaging pipelines, gateways, and channels)
│   └── spring-integration-file ... (Specific adapters to stream external files/data pools)
│
├── Spring Shell .......──> Builds terminal-based command-line tools
│   ├── spring-shell-core ......... (The terminal parsing engine and command UI)
│   └── spring-shell-standard ..... (Built-in CLI commands like help, clear, and exit)
│
└── Spring Framework ...──> The foundation engine managing the core mechanics
    ├── spring-aop ................ (Aspect-Oriented Programming for logging/transactions)
    ├── spring-web ................ (Web integration, REST clients, and HTTP filters)
    ├── spring-context ............ (The Application Context registry holding beans)
    └── spring-core ............... (The absolute bedrock IoC and DI container utils)`;

  const folderContent = `store/                              # The root project folder
├── .mvn/                           # Hidden folder storing Maven Wrapper configurations
│   └── wrapper/
│       ├── maven-wrapper.jar       # Tiny binary that downloads/boots the Maven version
│       └── maven-wrapper.properties# Properties file configuring the exact target Maven version
├── src/                            # Source code root
│   ├── main/                       # Production-ready code and assets
│   │   ├── java/                   # Root directory for all Java source code packages
│   │   │   └── com/
│   │   │       └── samyspring/
│   │   │           └── store/       # Main application package matching Group + Artifact
│   │   │               └── StoreApplication.java # Main entry point class with main method
│   │   └── resources/              # Non-code assets used by your application
│   │       ├── application.properties # Main configuration file (ports, DB URLs, log levels)
│   │       ├── static/             # Folder for static web frontend assets (HTML, CSS, JS)
│   │       └── templates/          # Folder for server-side UI engine templates (Thymeleaf)
│   └── test/                       # Test code root (isolated from production build)
│       └── java/                   # Root directory for unit tests and integration tests
├── mvnw                            # Executable Linux/macOS shell script for Maven Wrapper
├── mvnw.cmd                        # Executable Windows batch script for Maven Wrapper
├── pom.xml                         # Core configuration file managing versions & dependencies
└── target/                         # Autogenerated build output containing compiled .class & JARs`;

  const mvcContent = `[ SPRING WEB MVC ARCHITECTURE & REQUEST LIFECYCLE ]

1. HTTP Request (GET /api/v1/products/42)
       │
       ▼
2. DispatcherServlet ──────────> 3. HandlerMapping
(Central Front Controller)        (Finds matching @RestController method)
       │                                 │
       ▼                                 ▼
5. HttpMessageConverter <──────── 4. Controller & Service Execution
(Serializes Java DTO to JSON)     (@GetMapping method returns ResponseEntity<ProductDTO>)
       │
       ▼
6. HTTP 200 OK Response (Application/JSON)

───────────────────────────────────────────────────────────────────────
[ THE 3 MVC PILLARS IN SPRING BOOT ]

• MODEL (M)      : Represents domain data, Entities (@Entity), and Transfer DTOs (Records).
• VIEW (V)       : Formats response data. In REST APIs, Jackson converts models to JSON.
• CONTROLLER (C) : Intercepts HTTP requests (@RestController), validates DTOs (@Valid), & delegates to Service layer.`;

  const getCopyText = () => {
    if (activeTab === "ecosystem") return ecosystemContent;
    if (activeTab === "folder-structure") return folderContent;
    return mvcContent;
  };

  return (
    <section id="core" className="w-full py-16 px-5 sm:px-10 lg:px-12 max-w-[1400px]">
      
      {/* Section Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-8 pb-4 border-b border-[#D4AF37]/20 gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-[#D4AF37] uppercase tracking-widest">
            <span>VOLUME I</span>
            <span>—</span>
            <span>ECOSYSTEM & ARCHITECTURE BLUEPRINT</span>
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-[#F4F1EA] mt-1 tracking-tight">
            Spring Blueprint <span className="spring-gradient-text">& Directory Anatomy</span>
          </h2>
        </div>

        {/* View Switcher Tabs */}
        <div className="flex flex-wrap items-center gap-1.5 p-1 rounded-xl bg-[#1C1A12] border border-[#D4AF37]/30 shrink-0">
          <button
            onClick={() => setActiveTab("ecosystem")}
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
              activeTab === "ecosystem"
                ? "bg-[#D4AF37] text-[#14120B] shadow-[0_2px_10px_rgba(212,175,55,0.3)]"
                : "text-[#A69E8F] hover:text-white hover:bg-white/5"
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>The Spring Ecosystem</span>
          </button>

          <button
            onClick={() => setActiveTab("folder-structure")}
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
              activeTab === "folder-structure"
                ? "bg-[#D4AF37] text-[#14120B] shadow-[0_2px_10px_rgba(212,175,55,0.3)]"
                : "text-[#A69E8F] hover:text-white hover:bg-white/5"
            }`}
          >
            <FolderTree className="w-3.5 h-3.5" />
            <span>Folder Structure</span>
          </button>

          <button
            onClick={() => setActiveTab("mvc")}
            className={`flex items-center gap-2 px-3.5 py-2 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
              activeTab === "mvc"
                ? "bg-[#D4AF37] text-[#14120B] shadow-[0_2px_10px_rgba(212,175,55,0.3)]"
                : "text-[#A69E8F] hover:text-white hover:bg-white/5"
            }`}
          >
            <Cpu className="w-3.5 h-3.5" />
            <span>Spring MVC Mechanics</span>
          </button>
        </div>
      </div>

      {/* Main Terminal Window Display */}
      <div className="w-full rounded-2xl bg-[#14120B] border border-[#D4AF37]/30 shadow-[0_20px_60px_rgba(0,0,0,0.9)] overflow-hidden font-mono text-xs">
        
        {/* Terminal Titlebar */}
        <div className="px-5 py-3.5 bg-[#1C1A12] border-b border-[#D4AF37]/20 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-3 h-3 rounded-full bg-[#E76F51]/80" />
            <div className="w-3 h-3 rounded-full bg-[#D4AF37]/80" />
            <div className="w-3 h-3 rounded-full bg-[#6DB33F]/80" />
            <span className="ml-3 text-[11px] text-[#A69E8F] font-mono flex items-center gap-1.5">
              <Terminal className="w-3.5 h-3.5 text-[#D4AF37]" />
              {activeTab === "ecosystem"
                ? "spring-ecosystem-hierarchy.ascii"
                : activeTab === "folder-structure"
                ? "spring-boot-project-structure.tree"
                : "spring-mvc-architecture-flow.diagram"}
            </span>
          </div>

          <button
            onClick={() => handleCopy(getCopyText())}
            className="flex items-center gap-1.5 px-3 py-1 rounded-md bg-[#14120B] border border-[#D4AF37]/20 text-[11px] text-[#A69E8F] hover:text-white hover:border-[#D4AF37]/60 transition-all cursor-pointer"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-[#6DB33F]" />
                <span className="text-[#6DB33F]">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Architecture ASCII</span>
              </>
            )}
          </button>
        </div>

        {/* Terminal Content Body */}
        <div className="p-6 overflow-x-auto text-[#F4F1EA] leading-relaxed selection:bg-[#D4AF37]/30">
          {activeTab === "ecosystem" && (
            <pre className="font-mono text-xs sm:text-sm text-[#F4F1EA]">
              <code>
                {ecosystemContent.split("\n").map((line, i) => {
                  if (line.startsWith("[ THE SPRING ECOSYSTEM ]")) {
                    return <span key={i} className="text-[#D4AF37] font-bold block mb-2">{line}</span>;
                  }
                  if (line.includes("├── Spring ") || line.includes("└── Spring ")) {
                    const parts = line.split("──>");
                    return (
                      <div key={i} className="py-0.5">
                        <span className="text-[#6DB33F] font-bold">{parts[0]}</span>
                        {parts[1] && <span className="text-[#D4AF37]">──&gt;{parts[1]}</span>}
                      </div>
                    );
                  }
                  if (line.includes("(")) {
                    const commentIndex = line.indexOf("(");
                    const treePart = line.substring(0, commentIndex);
                    const commentPart = line.substring(commentIndex);
                    return (
                      <div key={i}>
                        <span className="text-[#A69E8F]">{treePart}</span>
                        <span className="text-[#A69E8F]/60 italic">{commentPart}</span>
                      </div>
                    );
                  }
                  return <div key={i} className="text-[#A69E8F]">{line}</div>;
                })}
              </code>
            </pre>
          )}

          {activeTab === "folder-structure" && (
            <pre className="font-mono text-xs sm:text-sm text-[#F4F1EA]">
              <code>
                {folderContent.split("\n").map((line, i) => {
                  if (line.includes("#")) {
                    const hashIndex = line.indexOf("#");
                    const pathPart = line.substring(0, hashIndex);
                    const commentPart = line.substring(hashIndex);
                    
                    const isKeyFile = pathPart.includes("StoreApplication.java") || pathPart.includes("pom.xml") || pathPart.includes("application.properties");
                    
                    return (
                      <div key={i} className="py-0.5 flex flex-wrap">
                        <span className={isKeyFile ? "text-[#D4AF37] font-bold" : "text-[#F4F1EA]"}>
                          {pathPart}
                        </span>
                        <span className="text-[#A69E8F]/70 italic">
                          {commentPart}
                        </span>
                      </div>
                    );
                  }
                  return <div key={i} className="text-[#A69E8F]">{line}</div>;
                })}
              </code>
            </pre>
          )}

          {activeTab === "mvc" && (
            <pre className="font-mono text-xs sm:text-sm text-[#F4F1EA]">
              <code>
                {mvcContent.split("\n").map((line, i) => {
                  if (line.startsWith("[ SPRING WEB MVC") || line.startsWith("[ THE 3 MVC PILLARS")) {
                    return <span key={i} className="text-[#D4AF37] font-bold block my-2">{line}</span>;
                  }
                  if (line.includes("• MODEL") || line.includes("• VIEW") || line.includes("• CONTROLLER")) {
                    return <div key={i} className="text-[#6DB33F] font-bold py-0.5">{line}</div>;
                  }
                  if (line.includes("DispatcherServlet") || line.includes("HandlerMapping") || line.includes("HttpMessageConverter")) {
                    return <div key={i} className="text-[#F4F1EA] font-semibold">{line}</div>;
                  }
                  return <div key={i} className="text-[#A69E8F]">{line}</div>;
                })}
              </code>
            </pre>
          )}
        </div>

        {/* Footer info bar */}
        <div className="px-5 py-2.5 bg-[#17150F] border-t border-[#D4AF37]/15 flex items-center justify-between text-[11px] text-[#A69E8F] font-mono">
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1.5">
              <FileCode2 className="w-3.5 h-3.5 text-[#6DB33F]" />
              Spring Boot 3.3.x / Web MVC
            </span>
            <span className="hidden sm:inline text-[#D4AF37]/50">|</span>
            <span className="hidden sm:inline">DispatcherServlet & Request Lifecycle</span>
          </div>
          <span className="text-[#D4AF37]">Primavera Volume I</span>
        </div>
      </div>

      {/* Spring MVC Deep-Dive Educational Grid */}
      <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Model Card */}
        <div className="p-6 rounded-2xl bg-[#1C1A12] border border-[#D4AF37]/20 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-mono text-[#D4AF37] tracking-widest uppercase">PILLAR I</span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-[#14120B] border border-[#D4AF37]/30 text-[#D4AF37] font-mono">Model (M)</span>
            </div>
            <h3 className="text-lg font-bold text-[#F4F1EA] mb-2">Data & State Representation</h3>
            <p className="text-xs text-[#A69E8F] leading-relaxed mb-4">
              Holds application state, database entities (<code className="text-[#D4AF37] font-mono">@Entity</code>), and immutable Data Transfer Objects (<code className="text-[#D4AF37] font-mono">Java Records</code>). Completely detached from HTTP presentation logic.
            </p>
          </div>
          <div className="p-3 rounded-xl bg-[#14120B] border border-[#D4AF37]/15 font-mono text-[11px] text-[#F4F1EA]">
            <span className="text-[#E76F51]">public record</span> ProductDTO(<br />
            &nbsp;&nbsp;Long id, String name, BigDecimal price<br />
            ) {}
          </div>
        </div>

        {/* View Card */}
        <div className="p-6 rounded-2xl bg-[#1C1A12] border border-[#D4AF37]/20 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-mono text-[#6DB33F] tracking-widest uppercase">PILLAR II</span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-[#14120B] border border-[#6DB33F]/30 text-[#6DB33F] font-mono">View (V)</span>
            </div>
            <h3 className="text-lg font-bold text-[#F4F1EA] mb-2">Presentation Serialization</h3>
            <p className="text-xs text-[#A69E8F] leading-relaxed mb-4">
              Renders the Model for the consumer. In REST APIs, Spring uses <code className="text-[#6DB33F] font-mono">Jackson2HttpMessageConverter</code> to automatically serialize Java objects into JSON payloads.
            </p>
          </div>
          <div className="p-3 rounded-xl bg-[#14120B] border border-[#6DB33F]/15 font-mono text-[11px] text-[#6DB33F]">
            &#123;<br />
            &nbsp;&nbsp;&quot;id&quot;: 42,<br />
            &nbsp;&nbsp;&quot;name&quot;: &quot;Spring Boot Guide&quot;<br />
            &#125;
          </div>
        </div>

        {/* Controller Card */}
        <div className="p-6 rounded-2xl bg-[#1C1A12] border border-[#D4AF37]/20 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-mono text-[#E76F51] tracking-widest uppercase">PILLAR III</span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-[#14120B] border border-[#E76F51]/30 text-[#E76F51] font-mono">Controller (C)</span>
            </div>
            <h3 className="text-lg font-bold text-[#F4F1EA] mb-2">Request Routing & Orchestration</h3>
            <p className="text-xs text-[#A69E8F] leading-relaxed mb-4">
              Intercepts incoming HTTP requests via <code className="text-[#E76F51] font-mono">@RestController</code>, validates payloads with <code className="text-[#E76F51] font-mono">@Valid</code>, and delegates business execution to the Service layer.
            </p>
          </div>
          <div className="p-3 rounded-xl bg-[#14120B] border border-[#E76F51]/15 font-mono text-[11px] text-[#F4F1EA]">
            <span className="text-[#E76F51]">@GetMapping</span>(<span className="text-[#6DB33F]">&quot;/products/&#123;id&#125;&quot;</span>)<br />
            <span className="text-[#D4AF37]">public</span> ProductDTO getProduct(...)
          </div>
        </div>

      </div>

    </section>
  );
}
